import React from 'react';
import { assets } from '../assets/assets';
import { motion } from 'framer-motion';

const GalleryPreview = () => {
  const previewImages = [
    assets.ai9,
    assets.ai3,
    // assets.ai5,
    assets.ai10,
    // assets.ai6,
    assets.ai11,
    assets.ai7,
    assets.ai1,
    assets.ai4,
    assets.ai8,
   
  ];

  return (
    <motion.div
      className="flex flex-col items-center my-16 px-4 sm:px-8"
      initial={{ opacity: 0, y: 80 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 1 }}
      viewport={{ once: true }}
    >
      <h2 className="text-3xl sm:text-4xl font-semibold mb-4 text-center">
        See What You Can Create
      </h2>
      <p className="text-gray-600 text-center max-w-2xl mb-10">
        Here's a glimpse of stunning images generated by our AI. Explore endless possibilities with just a few words.
      </p>

      {/* Masonry column layout */}
      <div className="columns-1 sm:columns-2 md:columns-3 lg:columns-4 gap-4 space-y-4 w-full max-w-7xl">
        {previewImages.map((img, index) => (
          <img
            key={index}
            src={img}
            alt={`Preview ${index + 1}`}
            className="w-full rounded-lg hover:scale-105 transition-transform cursor-pointer"
          />
        ))}
      </div>
    </motion.div>
  );
};

export default GalleryPreview;
